channels:
  - defaults
dependencies:
  - defaults::pandas
  - defaults::pip
  - defaults::scikit-learn
  - defaults::tenacity
  - defaults::pickle5
  - conda-forge::pyyaml
  - conda-forge::requests
  - conda-forge::openai
  - conda-forge::tqdm
  - conda-forge::python-dotenv
  - conda-forge::pandarallel
  - pip:
    - duckdb
